name: "node_24_app"
services:
  node:
    image: "node:24"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports: 
      - 3000:3000
    command: "tail -F anything"